
services:
  postgres-db:
    image: postgres:15-alpine # ambil dari docker hub
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    
    deploy:
      resources:
        limits:
          cpus: "0.5" 
          memory: 512M 
        reservations:
          memory: 128M 
      
  # backend-api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: go-fiber-api
  #   restart: always
  #   ports:
  #     - "3000:3000" # Map port Fiber
  #   environment:
  #     # BEST PRACTICE: Gunakan nama service database sebagai Host
  #     - DB_HOST=postgres-db 
  #     - DB_PORT=5432
  #     - DB_USER=${DB_USER:-root}
  #     - DB_PASSWORD=${DB_PASSWORD:-secret}
  #     - DB_NAME=${DB_NAME:-pos_db}
  #   depends_on:
  #     - postgres-db # Pastikan DB jalan duluan sebelum backend

  # Service Redis
  redis:
    image: redis:7-alpine
    container_name: order_redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass "${REDIS_PASSWORD}"
    volumes: 
      - redis_data:/data
    networks:
      - app_network

  # (Opsional) GUI untuk Redis supaya mudah debugging
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_gui
    environment:
      - REDIS_HOSTS=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - app_network

volumes:
  postgres-db-data:
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge

